#!/usr/bin/env python3
"""06 - Quality assurance. Writes data/processed/qa_report.txt and data/processed/qa.json.

Checks
  1. Provenance: every file under data/raw/agency matches the SHA-256 in PROVENANCE.txt.
  2. Reconstruction: every ALFRED vintage rebuilt from the cache matches the content hash in the manifest
     (this is the check a FedDrift user runs after rebuilding the FRED-sourced layer with their own key).
  3. Anchor agreement: the newest ALFRED vintage vs the agency file fetched directly from the agency.
  4. Negative control: NSA CPI should almost never be revised; compare with the SA CPI.
  5. Integrity: unique pair ids, valid ranges, no unknown rules or causes.
  6. Named spot checks for the author to confirm by hand.
"""

import hashlib
import json
import os
import re

import numpy as np
import pandas as pd

from fd_common import AGENCY_RAW, ALFRED_CACHE, MANIFESTS, PROCESSED, PROVENANCE_LOG, ROOT, load_panel, sha256_file

SPOT_CHECKS = [
    ("CPIAUCSL", "2026-02-13", "January-2026 CPI release: five years of SA indexes revised (expect earliest revised obs 2021-01)"),
    ("CPIAUCNS", "1988-02-26", "CPI reference base changed to 1982-84=100 (expect rebase_like = True)"),
    ("RSAFS", "2018-05-25", "Census annual retail revision with new MRTS sample and 2012 NAICS restatement"),
    ("DGORDER", "2025-05-27", "First ALFRED vintage carrying the M3 benchmark that Census dates to 2025-05-16"),
    ("RSAFS", "2022-12-15", "New MARTS sample introduced; Census says samples are linked, so a routine footprint is expected"),
    ("RSAFS", "2026-09-28", "Deep off-season revision (depth 140 months, mean 1.1%): unclassified, needs agency source"),
    ("PPIACO", "2026-09-10", "Routine PPI release: expect revision depth ~5 months (4-month recalculation)"),
    ("TSIFRGHT", "2026-10-01", "TSI release: expect most of the history revised (routine re-estimation)"),
]


# Explanations for anchor disagreements found on the 2026-10-03 snapshot. Each is a hypothesis for the author.
ANCHOR_NOTES = {
    "MRTSSM44X72USS": "the agency MRTS file was re-issued 2026-09-28 (same day as the deep RSAFS/RSXFS revision "
                      "back to 2015-01), while ALFRED's newest MRTS vintage is still 2026-09-16; every mismatch lies "
                      "in 2015-01..2026-07, i.e. the agency file already carries a revision ALFRED has not yet "
                      "vintaged. Timing difference, not a pipeline error. [VERIFY against the Census release]",
}


def vintage_hash(dates, values):
    s = "".join(f"{d},{v}\n" for d, v in sorted(zip(dates, values)))
    return hashlib.sha256(s.encode()).hexdigest()


def main():
    rep, qa = [], {}
    w = rep.append
    w("FedDrift QA report  (DRAFT - generated by code/06_qa.py; read before trusting any output)")
    w("=" * 88)

    # 1 provenance
    logged = {}
    for line in open(PROVENANCE_LOG, encoding="utf-8"):
        parts = [p.strip() for p in line.split("|")]
        logged[parts[1]] = parts[3].replace("sha256:", "")
    agency_files = [os.path.relpath(os.path.join(d, f), ROOT) for d, _, fs in os.walk(AGENCY_RAW) for f in fs]
    bad = [f for f in agency_files if logged.get(f) != sha256_file(os.path.join(ROOT, f))]
    qa["provenance_files"], qa["provenance_mismatch"] = len(agency_files), len(bad)
    w(f"\n1. PROVENANCE: {len(agency_files)} agency files, {len(bad)} hash mismatches {bad if bad else ''}")

    # 2 reconstruction
    w("\n2. RECONSTRUCTION (ALFRED cache vs published manifest hashes)")
    tot = mis = 0
    for p in load_panel():
        sid = p["series_id"]
        man = pd.read_csv(os.path.join(MANIFESTS, f"{sid}.vintages.csv"))
        j = json.load(open(os.path.join(ALFRED_CACHE, f"{sid}.observations.json")))
        df = pd.DataFrame(j["observations"])
        df = df[df.value != "."]
        m = 0
        for _, r in man.iterrows():
            live = df[(df.realtime_start <= r.vintage_date) & (df.realtime_end >= r.vintage_date)]
            m += vintage_hash(live.date.tolist(), live.value.tolist()) != r.vintage_sha256
        tot += len(man)
        mis += m
        w(f"   {sid:16s} {len(man):4d} vintages, {m} mismatches")
    qa["vintages_total"], qa["vintages_hash_mismatch"] = tot, mis

    # 3 anchor agreement
    w("\n3. ANCHOR AGREEMENT (newest ALFRED vintage vs agency file; tolerance = half a unit in the last published digit)")
    anchor = pd.read_csv(os.path.join(PROCESSED, "anchor_vintage.csv"), dtype={"value": float})
    agree = {}
    for p in load_panel():
        sid = p["series_id"]
        j = json.load(open(os.path.join(ALFRED_CACHE, f"{sid}.observations.json")))
        df = pd.DataFrame(j["observations"])
        latest = j["vintage_dates"][-1]
        live = df[(df.realtime_start <= latest) & (df.realtime_end >= latest) & (df.value != ".")]
        dec = live.value.map(lambda s: len(s.split(".")[1]) if "." in s else 0)
        tol = dict(zip(live.date, 0.5 * 10.0 ** (-dec) + 1e-12))
        alf = pd.Series(live.value.astype(float).values, index=live.date.values)
        a = anchor[anchor.series_id == sid].set_index("obs_date").value
        a = a[a.index >= "1947-01-01"]
        a = a[~a.index.duplicated()]
        common = alf.index.intersection(a.index)
        diff = (alf.loc[common] - a.loc[common]).abs()
        ok = pd.Series(diff.values <= pd.Series(tol).loc[common].values, index=common)
        mism = [(d, alf[d], a[d]) for d in common[~ok.values]][:5]
        only_agency = sorted(set(a.index) - set(alf.index))
        only_alfred = sorted(set(alf.index) - set(a.index))
        agree[sid] = {"alfred_vintage": latest, "common": int(len(common)), "match": int(ok.sum()),
                      "match_rate": round(float(ok.mean()), 6) if len(common) else None,
                      "only_in_agency": len(only_agency), "only_in_alfred": len(only_alfred),
                      "examples_mismatch": [[d, float(x), float(y)] for d, x, y in mism]}
        w(f"   {sid:16s} ALFRED {latest}  common {len(common):5d}  match {ok.mean() * 100:6.2f}%  "
          f"agency-only {len(only_agency):3d} {only_agency[-2:] if only_agency else ''}  "
          f"alfred-only {len(only_alfred):3d}" + (f"  e.g. {mism[:2]}" if mism else ""))
    qa["anchor_agreement"] = agree
    for sid, why in ANCHOR_NOTES.items():
        if agree.get(sid, {}).get("match_rate", 1) < 1:
            w(f"   NOTE {sid}: {why}")

    # 4 negative control
    ev = pd.read_csv(os.path.join(PROCESSED, "proposed_events.csv"))
    share = ev.groupby("series_id").apply(lambda g: (g.n_revised > 0).mean(), include_groups=False)
    qa["share_pairs_revised"] = {k: round(float(v), 4) for k, v in share.items()}
    w("\n4. NEGATIVE CONTROL (share of vintage pairs that revise at least one value)")
    for k in ["CPIAUCNS", "CPIAUCSL", "CPILFESL", "PPIACO", "RSAFSNA", "RSAFS"]:
        w(f"   {k:16s} {share[k] * 100:6.2f}%")
    nsa = ev[(ev.series_id == "CPIAUCNS") & (ev.n_revised > 0)]
    w(f"   CPIAUCNS revising vintages: {', '.join(nsa.vintage_next)}  (each is individually labeled)")

    # 5 integrity
    w("\n5. INTEGRITY")
    checks = {
        "pair_id unique": ev.pair_id.is_unique,
        "depth >= 0 where revised": bool((ev.revision_depth_months.dropna() >= 0).all()),
        "share_revised in [0,1]": bool(ev.share_revised.dropna().between(0, 1).all()),
        "every pair has a rule": bool(ev.proposed_rule.notna().all()),
        "vintage_next > vintage_prev": bool((ev.vintage_next > ev.vintage_prev).all()),
        "n_revised <= n_overlap": bool((ev.n_revised <= ev.n_overlap).all()),
    }
    for k, v in checks.items():
        w(f"   [{'PASS' if v else 'FAIL'}] {k}")
    qa["integrity"] = checks
    w(f"   rows: pairs {len(ev)}, drift events {int(ev.is_drift_event.sum())}, series {ev.series_id.nunique()}")

    # 6 spot checks
    w("\n6. NAMED SPOT CHECKS (author confirms each against the agency release, by hand)")
    for sid, v, why in SPOT_CHECKS:
        r = ev[(ev.series_id == sid) & (ev.vintage_next == v)]
        if r.empty:
            w(f"   [MISSING] {sid} {v}")
            continue
        r = r.iloc[0]
        w(f"   [ ] {r.pair_id}: rule {r.proposed_rule} -> {r.proposed_cause}; revised {r.n_revised}, "
          f"earliest {r.earliest_revised_obs}, depth {r.revision_depth_months}, mean|rev| {r.mean_abs_pct_revision}%")
        w(f"       why: {why}")

    open(os.path.join(PROCESSED, "qa_report.txt"), "w").write("\n".join(rep) + "\n")
    json.dump(qa, open(os.path.join(PROCESSED, "qa.json"), "w"), indent=1, default=str)
    print("\n".join(rep))


if __name__ == "__main__":
    main()
